# Generated by Django 5.2.7 on 2025-10-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'pending'), ('done', 'done')], default='open', max_length=20)),
            ],
        ),
    ]
